FROM node:alpine

RUN apk update && apk upgrade && mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json yarn.lock /usr/src/app/
RUN yarn

COPY . /usr/src/app

ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

CMD "yarn" "run" "dev"
