export const galaxiesMap = {
  technology: 'Technology',
  science: 'Science',
  movies_tv: 'Movies & Television',
  music: 'Music',
  art: 'Art',
  gaming: 'Gaming',
  podcasts_streams_videos: 'Podcasts, Streams & Videos',
  memes_internet: 'Memes & Internet Culture',
  funny: 'Funny',
  pics_gifs: 'Pics & Gifs',
  programming: 'Programming',
  news: 'News',
  politics: 'Politics',
  business_economics_finance: 'Business, Economics & Finance',
  marketplace_deals: 'Marketplace & Deals',
  animals_pets: 'Animals & Pets',
  outdoors_nature: 'Outdoors & Nature',
  reading_writing_literature: 'Reading, Writing & Literature',
  spirituality_religion: 'Spirituality & Religion',
  philosophy_ethics: 'Philosophy & Ethics',
  fitness_nutrition: 'Fitness & Nutrition',
  health: 'Medical & Mental Health',
  hobbies: 'Hobbies',
  sports: 'Sports',
  crypto: 'Crypto',
  anime: 'Anime',
  home_garden: 'Home & Garden',
  places_travel: 'Places & Travel',
  food_drink: 'Food & Drink',
  learning_education: 'Learning & Education',
  careers: 'Careers',
  family_relationships: 'Family & Relationships',
  law: 'Law',
  history: 'History',
  beauty_makeup: 'Beauty & Makeup',
  crafts_diy: 'Crafts & DIY',
  fashion: 'Fashion',
  celebrity: 'Celebrity',
  vehicles: 'Cars & Motor Vehicles',
  tabletop_games: 'Tabletop Games',
  military: 'Military',
  activism: 'Activism',
  culture_race_ethnicity: 'Culture, Race & Ethnicity',
  sexuality_gender: 'Sexual Orientation & Gender',
  mens_health: "Men's Health",
  womens_health: "Women's Health",
  addiction: 'Addiction Support',
  trauma: 'Trauma Support',
  nsfw: 'NSFW',
  meta: 'Meta/CometX'
}

export const galaxyFromValue = value =>
  Object.keys(galaxiesMap).find(key => galaxiesMap[key] === value)
