FROM node:alpine

RUN apk update && apk add git && apk add make && apk add gcc && apk add g++ && apk add python2 && mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json yarn.lock /usr/src/app/
RUN yarn

COPY . /usr/src/app

CMD "yarn" "run" "dev"
