FROM node:15-alpine

RUN apk update && apk upgrade && apk add git make gcc g++ python2 && mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json yarn.lock /usr/src/app/
RUN yarn

COPY . /usr/src/app

CMD "yarn" "run" "dev"
